### ISSUE TITLE
keyboard and touchpad not working anymore on MBP13,1

### ISSUE THREAD

**Issue by christophgysin** [cb22/macbook12-spi-driver#18]
Broken since  c90e4b4e577c2a4473b68910950fa30d0d8d5160.

Kernel 4.11rc8

**Comment by tudorbarascu** [comment]
I have the 13,1 mbpro + kernel 4.11rc8 and everything works. I built the driver from @roadrunner2 that should be the same as this one after the merge (haven't checked though).

**Comment by christophgysin** [comment]
Hmm, I bisected to this commit, and could reproduce the problem with and without that commit. After a reboot everything seems to work though. False alarm!
