### ISSUE TITLE
Proper function without DSDT patch

### ISSUE THREAD

**Issue by Dunedan** [cb22/macbook12-spi-driver#21]
I guess we all want to see this driver working without the need for patching the DSDT. While researching something else I stumbled upon a discussion Leif Liddy had with some ACPI kernel developers back in early 2016 (https://www.spinics.net/lists/linux-spi/msg06964.html).

In this discussion Lukas Wunner proposes a solution (https://www.spinics.net/lists/linux-spi/msg06968.html) which sounds pretty reasonable. So that could be a path to get it working without DSDT patching. Still somebody has to implement it.

**Comment by roadrunner2** [comment]
FYI, I'm working on a solution within the applespi driver alone, so that until proper fixes in the core happen folks have a solution.
