### ISSUE TITLE
Wrong key mapping for <>\ and § with swiss german keyboard layout

### ISSUE THREAD

**Issue by joelkraehemann** [cb22/macbook12-spi-driver#23]
Two keys aren't working as expected they are:

* key 1 below esc § °
* key 2 right to shift <>\

This keys aren't accessible to me since I use swiss german keyboard layout. There is probably something wrong with the mapping.

**Comment by Dunedan** [comment]
That's what the new option `iso_layout` is for. :wink:
See #12 and #17 for more details.

**Comment by cb22** [comment]
This was fixed by #17 as far as I can tell; do re-open if that's not the case.
