### ISSUE TITLE
Driver not working

### ISSUE THREAD

**Issue by choelzl** [cb22/macbook12-spi-driver#24]
I made changes to the dsdt and compiled my kernel but the driver still doesnt work (the modified dsdt doesnt seem to get loaded). Could someone assist me ?

**Comment by john-morton** [comment]
I've just been through this exercise, let me know your email address and I'll send you some notes that were applicable to my MacBook 2015 12" model (which hopefully help!).

**Comment by choelzl** [comment]
choelzl.github@forward.cat
I have the MacBook 2016 12" just in case.

**Comment by john-morton** [comment]
@choelzl - did you receive my email (sent last night)? Apologies for the delay, I was moving house and had no access to any Internet!
