### ISSUE TITLE
Caps Lock LED doesn't work

### ISSUE THREAD

**Issue by cgutman** [cb22/macbook12-spi-driver#3]
We probably need to capture the SPI transfers that happen on Windows and macOS to turn the LED on and off to make this work.

**Comment by cb22** [comment]
I captured the packet needed to do this a while back, let me dig them up. If you'd like to experiment with sniffing the SPI data yourself, here's how I did it in Windows 10:

> It's possible to get Windows to dump everything it sends on what it calls SPB - basically SPI & I2C. Open the Event Viewer and enable View -> Show Analytic and Debug Logs. Then head to Application and Services Logs -> Microsoft -> Windows -> SPB-ClassExtension. Right click on Analytic and enable it - all events will be logged. Disable it when done, and look for the 1023 events, and view the details tab - they'll give you the full buffer contents. Other events will let you know things like the direction of the transfer, etc.

There are still quite a few packets with unknown contents. Definitely a cool one to reverse would be the "force click" that happens; but to the best of my knowledge that only happens under macOS.

**Comment by roadrunner2** [comment]
Can you dig up those traces? I'd love to add this functionality (and submit a pull request).

**Comment by cb22** [comment]
@roadrunner2 I don't think I have them anymore, but I'll do a capture from Windows. Sorry, I haven't had much time to give to this driver as of late

**Comment by roadrunner2** [comment]
I got some traces from @tudorbarascu over on issue #6, and am making progress on this - the basics are working, but still have some reliability issues. Will send a pull request when it's ready.
