### ISSUE TITLE
applespi not working with new uuid framework in 4.13

### ISSUE THREAD

**Issue by Dunedan** [cb22/macbook12-spi-driver#37]
Trying to compile `applespi` for Linux 4.13 fails with some error messages related to the introduction of the new UUID framework in Linux 4.13 (http://lkml.iu.edu/hypermail/linux/kernel/1707.0/00324.html)

**Comment by roadrunner2** [comment]
@Dunedan I just created a patch for this in a [kernel-4.13-fixes branch](/roadrunner2/macbook12-spi-driver/commits/kernel-4.13-fixes), but I've only tested that it compiles. If you can verify that it runs correctly too, I'll submit it as a pull request.

**Comment by Dunedan** [comment]
Writing this on my MacBookPro13,2 with Kernel 4.13. Your patch works fine. :+1:

**Comment by roadrunner2** [comment]
@Dunedan Thanks for testing!
