### ISSUE TITLE
Macbook14,3 needs two loading to get keyboard backlights

### ISSUE THREAD

**Issue by aapo** [cb22/macbook12-spi-driver#58]
On Macbook14,3 it needs two modprobing to get keyboard backlights.
If I autoload applespi during boot, keyboard works, but no backlights at all. After "rmmod applespi ; modprobe applespi" backlights work.

If I don't load applespi during boot, I need "rmmod applespi ; modprobe applespi ; mmod applespi ; modprobe applespi" to get lights.

**Comment by Dunedan** [comment]
Is this problem still there after your Touch Bar problem (https://github.com/Dunedan/mbp-2016-linux/issues/52) got fixed? Just to make sure those two problems aren't related.

**Comment by aapo** [comment]
This got fixed. (It also needs firmware-files in /boot/efi/EFI/APPLE).
