### ISSUE TITLE
MacBookPro14,3: touchbar is off after resume from suspend

### ISSUE THREAD

**Issue by arno01** [cb22/macbook12-spi-driver#61]
When my MacBookPro14,3 resumes back from suspend the touchbar is off (black).

Reloading the kernel module doesn't help:

```
# modprobe -r appletb ; sleep 2 ; modprobe appletb
```

Linux kernel: 4.16-rc3
Distro: Ubuntu 16.04

Any guesses, ideas?

**Comment by roadrunner2** [comment]
Yes, this is a known issue - please see roadrunner2/macbook12-spi-driver#3 . Need help to debug/resolve the issue.

Closing as a duplicate - please continue discussions on the original ticket. Thanks.
