### ISSUE TITLE
dkms: command not found

### ISSUE THREAD

**Issue by KeelanO** [cb22/macbook12-spi-driver#74]
all i get when i try to use the dkms command is dkms: command not found

**Comment by roadrunner2** [comment]
Did you install the dkms package as instructed?

**Comment by KeelanO** [comment]
Whenever I try a command such as “dkms install -m applespi -v 0.1“, the error appears

**Comment by roadrunner2** [comment]
Please read the instructions again: did you run `sudo apt install dkms` (or whatever the equivalent is for your distro)?

**Comment by KeelanO** [comment]
It says E: Unable to locate package dkms

**Comment by KeelanO** [comment]
I got it. I had to update my repo

**Comment by roadrunner2** [comment]
@KeelanO Do you mind closing this issue since the problem has been resolved? TIA.
